# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGridLayout,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpacerItem, QSpinBox, QStackedWidget, QTabWidget,
    QWidget)
import MainWindowResources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setWindowModality(Qt.WindowModality.NonModal)
        Form.resize(1080, 389)
        Form.setMinimumSize(QSize(1080, 389))
        Form.setMaximumSize(QSize(1080, 389))
        palette = QPalette()
        brush = QBrush(QColor(85, 85, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Active, QPalette.Link, brush)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush)
        Form.setPalette(palette)
        font = QFont()
        font.setFamilies([u"RobotoMono Nerd Font"])
        font.setPointSize(11)
        Form.setFont(font)
        Form.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        Form.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u"pallet.ico", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(True)
        Form.setLocale(QLocale(QLocale.German, QLocale.Germany))
        Form.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QRect(0, 0, 1080, 389))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.stackedWidget.setLocale(QLocale(QLocale.German, QLocale.Germany))
        self.stackedWidget.setFrameShape(QFrame.Shape.NoFrame)
        self.MainMenu = QWidget()
        self.MainMenu.setObjectName(u"MainMenu")
        self.ButtonSettings = QPushButton(self.MainMenu)
        self.ButtonSettings.setObjectName(u"ButtonSettings")
        self.ButtonSettings.setGeometry(QRect(10, 10, 61, 61))
        sizePolicy.setHeightForWidth(self.ButtonSettings.sizePolicy().hasHeightForWidth())
        self.ButtonSettings.setSizePolicy(sizePolicy)
        self.ButtonSettings.setAutoFillBackground(False)
        self.ButtonSettings.setFlat(True)
        self.checkBoxEinzelpaket = QCheckBox(self.MainMenu)
        self.checkBoxEinzelpaket.setObjectName(u"checkBoxEinzelpaket")
        self.checkBoxEinzelpaket.setEnabled(False)
        self.checkBoxEinzelpaket.setGeometry(QRect(80, 310, 171, 61))
        font1 = QFont()
        font1.setFamilies([u"RobotoMono Nerd Font"])
        font1.setPointSize(16)
        self.checkBoxEinzelpaket.setFont(font1)
        self.checkBoxEinzelpaket.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.checkBoxEinzelpaket.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.ButtonDatenSenden = QPushButton(self.MainMenu)
        self.ButtonDatenSenden.setObjectName(u"ButtonDatenSenden")
        self.ButtonDatenSenden.setEnabled(False)
        self.ButtonDatenSenden.setGeometry(QRect(540, 310, 261, 61))
        self.ButtonDatenSenden.setFont(font1)
        self.ButtonDatenSenden.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonOpenParameterRoboter = QPushButton(self.MainMenu)
        self.ButtonOpenParameterRoboter.setObjectName(u"ButtonOpenParameterRoboter")
        self.ButtonOpenParameterRoboter.setEnabled(False)
        self.ButtonOpenParameterRoboter.setGeometry(QRect(260, 310, 261, 61))
        self.ButtonOpenParameterRoboter.setFont(font1)
        self.ButtonOpenParameterRoboter.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_7 = QLabel(self.MainMenu)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(820, 70, 250, 250))
        self.label_7.setPixmap(QPixmap(u":/Szaidel Logo/imgs/szaidel-transparent.png"))
        self.label_7.setScaledContents(True)
        self.LabelPalletenplanInfo = QLabel(self.MainMenu)
        self.LabelPalletenplanInfo.setObjectName(u"LabelPalletenplanInfo")
        self.LabelPalletenplanInfo.setGeometry(QRect(250, 40, 471, 31))
        font2 = QFont()
        font2.setFamilies([u"RobotoMono Nerd Font"])
        font2.setPointSize(18)
        font2.setUnderline(False)
        font2.setKerning(True)
        self.LabelPalletenplanInfo.setFont(font2)
        self.LabelPalletenplanInfo.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignHCenter)
        self.label_9 = QLabel(self.MainMenu)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(720, 200, 121, 41))
        self.label_9.setFont(font1)
        self.label_9.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_10 = QLabel(self.MainMenu)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(720, 250, 121, 41))
        self.label_10.setFont(font1)
        self.label_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.EingabePallettenplan = QLineEdit(self.MainMenu)
        self.EingabePallettenplan.setObjectName(u"EingabePallettenplan")
        self.EingabePallettenplan.setGeometry(QRect(252, 90, 461, 39))
        self.EingabePallettenplan.setMinimumSize(QSize(0, 39))
        self.EingabePallettenplan.setMaximumSize(QSize(16777215, 39))
        self.EingabePallettenplan.setFont(font1)
        self.label_4 = QLabel(self.MainMenu)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 248, 241, 41))
        self.label_4.setFont(font1)
        self.label_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label = QLabel(self.MainMenu)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 90, 241, 41))
        self.label.setFont(font1)
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.LadePallettenplan = QPushButton(self.MainMenu)
        self.LadePallettenplan.setObjectName(u"LadePallettenplan")
        self.LadePallettenplan.setGeometry(QRect(725, 80, 60, 60))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.LadePallettenplan.sizePolicy().hasHeightForWidth())
        self.LadePallettenplan.setSizePolicy(sizePolicy1)
        self.LadePallettenplan.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.LadePallettenplan.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        icon1 = QIcon()
        icon1.addFile(u":/Misc/imgs/load.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.LadePallettenplan.setIcon(icon1)
        self.LadePallettenplan.setIconSize(QSize(60, 60))
        self.LadePallettenplan.setFlat(True)
        self.label_2 = QLabel(self.MainMenu)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 140, 241, 41))
        self.label_2.setFont(font1)
        self.label_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.EingabeStartlage = QSpinBox(self.MainMenu)
        self.EingabeStartlage.setObjectName(u"EingabeStartlage")
        self.EingabeStartlage.setEnabled(False)
        self.EingabeStartlage.setGeometry(QRect(252, 144, 461, 39))
        sizePolicy1.setHeightForWidth(self.EingabeStartlage.sizePolicy().hasHeightForWidth())
        self.EingabeStartlage.setSizePolicy(sizePolicy1)
        self.EingabeStartlage.setMinimumSize(QSize(0, 39))
        self.EingabeStartlage.setMaximumSize(QSize(16777215, 39))
        self.EingabeStartlage.setFont(font1)
        self.EingabeStartlage.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.EingabeStartlage.setMinimum(1)
        self.EingabeStartlage.setValue(1)
        self.label_3 = QLabel(self.MainMenu)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 194, 241, 41))
        self.label_3.setFont(font1)
        self.label_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.EingabeKartonGewicht = QLineEdit(self.MainMenu)
        self.EingabeKartonGewicht.setObjectName(u"EingabeKartonGewicht")
        self.EingabeKartonGewicht.setEnabled(False)
        self.EingabeKartonGewicht.setGeometry(QRect(252, 252, 461, 39))
        self.EingabeKartonGewicht.setMinimumSize(QSize(0, 39))
        self.EingabeKartonGewicht.setFont(font1)
        self.EingabeKartonGewicht.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.EingabeKartonhoehe = QLineEdit(self.MainMenu)
        self.EingabeKartonhoehe.setObjectName(u"EingabeKartonhoehe")
        self.EingabeKartonhoehe.setEnabled(False)
        self.EingabeKartonhoehe.setGeometry(QRect(252, 198, 461, 39))
        self.EingabeKartonhoehe.setMinimumSize(QSize(0, 39))
        self.EingabeKartonhoehe.setMaximumSize(QSize(16777215, 39))
        self.EingabeKartonhoehe.setFont(font1)
        self.EingabeKartonhoehe.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.EingabeKartonhoehe.setClearButtonEnabled(False)
        self.stackedWidget.addWidget(self.MainMenu)
        self.RoboParameter = QWidget()
        self.RoboParameter.setObjectName(u"RoboParameter")
        self.tabWidget = QTabWidget(self.RoboParameter)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1080, 389))
        self.tabWidget.setFont(font1)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.Roboter = QWidget()
        self.Roboter.setObjectName(u"Roboter")
        self.ButtonZurueck = QPushButton(self.Roboter)
        self.ButtonZurueck.setObjectName(u"ButtonZurueck")
        self.ButtonZurueck.setGeometry(QRect(0, 140, 81, 81))
        icon2 = QIcon()
        icon2.addFile(u":/Misc/imgs/zurueck.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.ButtonZurueck.setIcon(icon2)
        self.ButtonZurueck.setIconSize(QSize(81, 81))
        self.ButtonZurueck.setFlat(True)
        self.ImageSzaidelLogoBig = QLabel(self.Roboter)
        self.ImageSzaidelLogoBig.setObjectName(u"ImageSzaidelLogoBig")
        self.ImageSzaidelLogoBig.setGeometry(QRect(270, -35, 600, 337))
        self.ImageSzaidelLogoBig.setSizeIncrement(QSize(0, 0))
        self.ImageSzaidelLogoBig.setPixmap(QPixmap(u":/Szaidel Logo/imgs/logoszaidel-transparent-big.png"))
        self.ImageSzaidelLogoBig.setScaledContents(True)
        self.ImageSzaidelLogoBig.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.ButtonRoboterStop = QPushButton(self.Roboter)
        self.ButtonRoboterStop.setObjectName(u"ButtonRoboterStop")
        self.ButtonRoboterStop.setGeometry(QRect(700, 70, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterStop.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterStop.setSizePolicy(sizePolicy)
        self.ButtonRoboterStop.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterStop.setFont(font1)
        self.ButtonRoboterStart = QPushButton(self.Roboter)
        self.ButtonRoboterStart.setObjectName(u"ButtonRoboterStart")
        self.ButtonRoboterStart.setGeometry(QRect(100, 70, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterStart.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterStart.setSizePolicy(sizePolicy)
        self.ButtonRoboterStart.setMinimumSize(QSize(300, 0))
        self.ButtonRoboterStart.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterStart.setFont(font1)
        self.ButtonStopRPCServer = QPushButton(self.Roboter)
        self.ButtonStopRPCServer.setObjectName(u"ButtonStopRPCServer")
        self.ButtonStopRPCServer.setGeometry(QRect(700, 220, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonStopRPCServer.sizePolicy().hasHeightForWidth())
        self.ButtonStopRPCServer.setSizePolicy(sizePolicy)
        self.ButtonStopRPCServer.setMaximumSize(QSize(350, 16777215))
        self.ButtonStopRPCServer.setFont(font1)
        self.ButtonRoboterPause = QPushButton(self.Roboter)
        self.ButtonRoboterPause.setObjectName(u"ButtonRoboterPause")
        self.ButtonRoboterPause.setGeometry(QRect(100, 220, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterPause.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterPause.setSizePolicy(sizePolicy)
        self.ButtonRoboterPause.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterPause.setFont(font1)
        self.tabWidget.addTab(self.Roboter, "")
        self.ImageSzaidelLogoBig.raise_()
        self.ButtonZurueck.raise_()
        self.ButtonRoboterPause.raise_()
        self.ButtonRoboterStart.raise_()
        self.ButtonRoboterStop.raise_()
        self.ButtonStopRPCServer.raise_()
        self.Aufnahme = QWidget()
        self.Aufnahme.setObjectName(u"Aufnahme")
        self.ButtonZurueck_2 = QPushButton(self.Aufnahme)
        self.ButtonZurueck_2.setObjectName(u"ButtonZurueck_2")
        self.ButtonZurueck_2.setGeometry(QRect(0, 140, 81, 81))
        self.ButtonZurueck_2.setIcon(icon2)
        self.ButtonZurueck_2.setIconSize(QSize(81, 81))
        self.ButtonZurueck_2.setFlat(True)
        self.ImageAufnahmePos = QLabel(self.Aufnahme)
        self.ImageAufnahmePos.setObjectName(u"ImageAufnahmePos")
        self.ImageAufnahmePos.setGeometry(QRect(80, 40, 390, 270))
        self.ImageAufnahmePos.setFrameShape(QFrame.Shape.Box)
        self.ImageAufnahmePos.setPixmap(QPixmap(u":/Aufnahme/imgs/Aufnahmepos.png"))
        self.ImageAufnahmePos.setScaledContents(True)
        self.label_5 = QLabel(self.Aufnahme)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(490, 60, 411, 31))
        self.label_5.setFont(font1)
        self.label_5.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.label_6 = QLabel(self.Aufnahme)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(490, 160, 411, 31))
        self.label_6.setFont(font1)
        self.label_6.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.EingabeVerschiebungX = QSpinBox(self.Aufnahme)
        self.EingabeVerschiebungX.setObjectName(u"EingabeVerschiebungX")
        self.EingabeVerschiebungX.setGeometry(QRect(910, 60, 141, 41))
        self.EingabeVerschiebungX.setMinimum(-20)
        self.EingabeVerschiebungX.setMaximum(20)
        self.EingabeVerschiebungY = QSpinBox(self.Aufnahme)
        self.EingabeVerschiebungY.setObjectName(u"EingabeVerschiebungY")
        self.EingabeVerschiebungY.setGeometry(QRect(910, 160, 141, 41))
        self.EingabeVerschiebungY.setMinimum(-20)
        self.EingabeVerschiebungY.setMaximum(20)
        self.ButtonDatenSenden_2 = QPushButton(self.Aufnahme)
        self.ButtonDatenSenden_2.setObjectName(u"ButtonDatenSenden_2")
        self.ButtonDatenSenden_2.setGeometry(QRect(480, 250, 571, 91))
        self.ButtonDatenSenden_2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.addTab(self.Aufnahme, "")
        self.stackedWidget.addWidget(self.RoboParameter)
        self.Settings = QWidget()
        self.Settings.setObjectName(u"Settings")
        self.gridLayoutWidget_2 = QWidget(self.Settings)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(20, 20, 1041, 341))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Button_OpenTerminal = QPushButton(self.gridLayoutWidget_2)
        self.Button_OpenTerminal.setObjectName(u"Button_OpenTerminal")
        self.Button_OpenTerminal.setFont(font1)

        self.gridLayout_2.addWidget(self.Button_OpenTerminal, 1, 0, 1, 1)

        self.Button_OpenExplorer = QPushButton(self.gridLayoutWidget_2)
        self.Button_OpenExplorer.setObjectName(u"Button_OpenExplorer")
        self.Button_OpenExplorer.setFont(font1)

        self.gridLayout_2.addWidget(self.Button_OpenExplorer, 0, 0, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer, 0, 1, 1, 1)

        self.stackedWidget.addWidget(self.Settings)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(1)
        self.ButtonSettings.setDefault(False)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Palletierer", None))
        self.ButtonSettings.setText("")
        self.checkBoxEinzelpaket.setText(QCoreApplication.translate("Form", u"Einzelpaket", None))
        self.ButtonDatenSenden.setText(QCoreApplication.translate("Form", u"Daten Senden", None))
        self.ButtonOpenParameterRoboter.setText(QCoreApplication.translate("Form", u"Parameter Roboter", None))
        self.label_7.setText("")
        self.LabelPalletenplanInfo.setText(QCoreApplication.translate("Form", u"Kein Pallettenplan geladen", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>mm</p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>kg</p></body></html>", None))
        self.EingabePallettenplan.setPlaceholderText(QCoreApplication.translate("Form", u"z.B: 699-00120", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Gewicht: </p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Palletierplan: </p></body></html>", None))
        self.LadePallettenplan.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Startlage: </p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Kartonh\u00f6he: </p></body></html>", None))
        self.ButtonZurueck.setText("")
        self.ImageSzaidelLogoBig.setText("")
        self.ButtonRoboterStop.setText(QCoreApplication.translate("Form", u"Roboter Stop", None))
        self.ButtonRoboterStart.setText(QCoreApplication.translate("Form", u"Roboter Start", None))
        self.ButtonStopRPCServer.setText(QCoreApplication.translate("Form", u"Stop RPC Server", None))
        self.ButtonRoboterPause.setText(QCoreApplication.translate("Form", u"Roboter Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Roboter), QCoreApplication.translate("Form", u"Roboter", None))
        self.ButtonZurueck_2.setText("")
        self.ImageAufnahmePos.setText("")
#if QT_CONFIG(whatsthis)
        self.label_5.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Gibt die Verschiebung in Richtung x an.</p><p>min. -20mm</p><p>max.  20mm</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_5.setText(QCoreApplication.translate("Form", u"verschieben in Richtung x von:", None))
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Gibt die Verschiebung in Richtung y an.</p><p>min. -20mm</p><p>max. 20mm</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_6.setText(QCoreApplication.translate("Form", u"verschieben in Richtung y von:", None))
        self.EingabeVerschiebungX.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.EingabeVerschiebungY.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.ButtonDatenSenden_2.setText(QCoreApplication.translate("Form", u"Daten senden", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Aufnahme), QCoreApplication.translate("Form", u"Aufnahme", None))
        self.Button_OpenTerminal.setText(QCoreApplication.translate("Form", u"Open Terminal", None))
        self.Button_OpenExplorer.setText(QCoreApplication.translate("Form", u"Open Explorer", None))
    # retranslateUi

