# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFormLayout, QFrame,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QSpinBox, QStackedWidget, QTabWidget, QWidget)
from . import MainWindowResources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setWindowModality(Qt.WindowModality.NonModal)
        Form.resize(1280, 390)
        Form.setMinimumSize(QSize(1280, 390))
        Form.setMaximumSize(QSize(1280, 390))
        palette = QPalette()
        brush = QBrush(QColor(85, 85, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Active, QPalette.Link, brush)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush)
        Form.setPalette(palette)
        font = QFont()
        font.setFamilies([u"RobotoMono Nerd Font"])
        font.setPointSize(11)
        Form.setFont(font)
        Form.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        Form.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u"pallet.ico", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(True)
        Form.setLocale(QLocale(QLocale.German, QLocale.Germany))
        Form.setInputMethodHints(Qt.InputMethodHint.ImhNone)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QRect(0, 0, 1280, 390))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.stackedWidget.setLocale(QLocale(QLocale.German, QLocale.Germany))
        self.stackedWidget.setFrameShape(QFrame.Shape.NoFrame)
        self.MainMenu = QWidget()
        self.MainMenu.setObjectName(u"MainMenu")
        self.ButtonSettings = QPushButton(self.MainMenu)
        self.ButtonSettings.setObjectName(u"ButtonSettings")
        self.ButtonSettings.setGeometry(QRect(10, 10, 61, 61))
        sizePolicy.setHeightForWidth(self.ButtonSettings.sizePolicy().hasHeightForWidth())
        self.ButtonSettings.setSizePolicy(sizePolicy)
        self.ButtonSettings.setAutoFillBackground(False)
        self.ButtonSettings.setFlat(True)
        self.checkBoxEinzelpaket = QCheckBox(self.MainMenu)
        self.checkBoxEinzelpaket.setObjectName(u"checkBoxEinzelpaket")
        self.checkBoxEinzelpaket.setEnabled(False)
        self.checkBoxEinzelpaket.setGeometry(QRect(150, 310, 171, 61))
        font1 = QFont()
        font1.setFamilies([u"RobotoMono Nerd Font"])
        font1.setPointSize(16)
        self.checkBoxEinzelpaket.setFont(font1)
        self.checkBoxEinzelpaket.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.checkBoxEinzelpaket.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.ButtonDatenSenden = QPushButton(self.MainMenu)
        self.ButtonDatenSenden.setObjectName(u"ButtonDatenSenden")
        self.ButtonDatenSenden.setEnabled(False)
        self.ButtonDatenSenden.setGeometry(QRect(610, 310, 261, 61))
        self.ButtonDatenSenden.setFont(font1)
        self.ButtonDatenSenden.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonOpenParameterRoboter = QPushButton(self.MainMenu)
        self.ButtonOpenParameterRoboter.setObjectName(u"ButtonOpenParameterRoboter")
        self.ButtonOpenParameterRoboter.setEnabled(False)
        self.ButtonOpenParameterRoboter.setGeometry(QRect(330, 310, 261, 61))
        self.ButtonOpenParameterRoboter.setFont(font1)
        self.ButtonOpenParameterRoboter.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.label_7 = QLabel(self.MainMenu)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(940, 70, 250, 250))
        self.label_7.setPixmap(QPixmap(u":/Szaidel Logo/imgs/szaidel-transparent.png"))
        self.label_7.setScaledContents(True)
        self.LabelPalletenplanInfo = QLabel(self.MainMenu)
        self.LabelPalletenplanInfo.setObjectName(u"LabelPalletenplanInfo")
        self.LabelPalletenplanInfo.setGeometry(QRect(320, 40, 471, 31))
        font2 = QFont()
        font2.setFamilies([u"RobotoMono Nerd Font"])
        font2.setPointSize(18)
        font2.setUnderline(False)
        font2.setKerning(True)
        self.LabelPalletenplanInfo.setFont(font2)
        self.LabelPalletenplanInfo.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignHCenter)
        self.label_9 = QLabel(self.MainMenu)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(790, 200, 121, 41))
        self.label_9.setFont(font1)
        self.label_9.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label_10 = QLabel(self.MainMenu)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(790, 250, 121, 41))
        self.label_10.setFont(font1)
        self.label_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.EingabePallettenplan = QLineEdit(self.MainMenu)
        self.EingabePallettenplan.setObjectName(u"EingabePallettenplan")
        self.EingabePallettenplan.setGeometry(QRect(322, 90, 461, 39))
        self.EingabePallettenplan.setMinimumSize(QSize(0, 39))
        self.EingabePallettenplan.setMaximumSize(QSize(16777215, 39))
        self.EingabePallettenplan.setFont(font1)
        self.label_4 = QLabel(self.MainMenu)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 248, 241, 41))
        self.label_4.setFont(font1)
        self.label_4.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label = QLabel(self.MainMenu)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 90, 241, 41))
        self.label.setFont(font1)
        self.label.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.LadePallettenplan = QPushButton(self.MainMenu)
        self.LadePallettenplan.setObjectName(u"LadePallettenplan")
        self.LadePallettenplan.setGeometry(QRect(795, 80, 60, 60))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.LadePallettenplan.sizePolicy().hasHeightForWidth())
        self.LadePallettenplan.setSizePolicy(sizePolicy1)
        self.LadePallettenplan.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.LadePallettenplan.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        icon1 = QIcon()
        icon1.addFile(u":/Misc/imgs/load.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.LadePallettenplan.setIcon(icon1)
        self.LadePallettenplan.setIconSize(QSize(60, 60))
        self.LadePallettenplan.setFlat(True)
        self.label_2 = QLabel(self.MainMenu)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 140, 241, 41))
        self.label_2.setFont(font1)
        self.label_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.EingabeStartlage = QSpinBox(self.MainMenu)
        self.EingabeStartlage.setObjectName(u"EingabeStartlage")
        self.EingabeStartlage.setEnabled(False)
        self.EingabeStartlage.setGeometry(QRect(322, 144, 461, 39))
        sizePolicy1.setHeightForWidth(self.EingabeStartlage.sizePolicy().hasHeightForWidth())
        self.EingabeStartlage.setSizePolicy(sizePolicy1)
        self.EingabeStartlage.setMinimumSize(QSize(0, 39))
        self.EingabeStartlage.setMaximumSize(QSize(16777215, 39))
        self.EingabeStartlage.setFont(font1)
        self.EingabeStartlage.setCursor(QCursor(Qt.CursorShape.IBeamCursor))
        self.EingabeStartlage.setMinimum(1)
        self.EingabeStartlage.setValue(1)
        self.label_3 = QLabel(self.MainMenu)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 194, 241, 41))
        self.label_3.setFont(font1)
        self.label_3.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.EingabeKartonGewicht = QLineEdit(self.MainMenu)
        self.EingabeKartonGewicht.setObjectName(u"EingabeKartonGewicht")
        self.EingabeKartonGewicht.setEnabled(False)
        self.EingabeKartonGewicht.setGeometry(QRect(322, 252, 461, 39))
        self.EingabeKartonGewicht.setMinimumSize(QSize(0, 39))
        self.EingabeKartonGewicht.setFont(font1)
        self.EingabeKartonGewicht.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly|Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.EingabeKartonhoehe = QLineEdit(self.MainMenu)
        self.EingabeKartonhoehe.setObjectName(u"EingabeKartonhoehe")
        self.EingabeKartonhoehe.setEnabled(False)
        self.EingabeKartonhoehe.setGeometry(QRect(322, 198, 461, 39))
        self.EingabeKartonhoehe.setMinimumSize(QSize(0, 39))
        self.EingabeKartonhoehe.setMaximumSize(QSize(16777215, 39))
        self.EingabeKartonhoehe.setFont(font1)
        self.EingabeKartonhoehe.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.EingabeKartonhoehe.setClearButtonEnabled(False)
        self.stackedWidget.addWidget(self.MainMenu)
        self.RoboParameter = QWidget()
        self.RoboParameter.setObjectName(u"RoboParameter")
        self.tabWidget = QTabWidget(self.RoboParameter)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1280, 390))
        self.tabWidget.setFont(font1)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.Roboter = QWidget()
        self.Roboter.setObjectName(u"Roboter")
        self.ButtonZurueck = QPushButton(self.Roboter)
        self.ButtonZurueck.setObjectName(u"ButtonZurueck")
        self.ButtonZurueck.setGeometry(QRect(0, 140, 81, 81))
        self.ButtonZurueck.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/Misc/imgs/zurueck.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.ButtonZurueck.setIcon(icon2)
        self.ButtonZurueck.setIconSize(QSize(81, 81))
        self.ButtonZurueck.setFlat(True)
        self.ImageSzaidelLogoBig = QLabel(self.Roboter)
        self.ImageSzaidelLogoBig.setObjectName(u"ImageSzaidelLogoBig")
        self.ImageSzaidelLogoBig.setGeometry(QRect(360, -35, 600, 337))
        self.ImageSzaidelLogoBig.setSizeIncrement(QSize(0, 0))
        self.ImageSzaidelLogoBig.setPixmap(QPixmap(u":/Szaidel Logo/imgs/logoszaidel-transparent-big.png"))
        self.ImageSzaidelLogoBig.setScaledContents(True)
        self.ImageSzaidelLogoBig.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.ButtonRoboterStop = QPushButton(self.Roboter)
        self.ButtonRoboterStop.setObjectName(u"ButtonRoboterStop")
        self.ButtonRoboterStop.setGeometry(QRect(830, 70, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterStop.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterStop.setSizePolicy(sizePolicy)
        self.ButtonRoboterStop.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterStop.setFont(font1)
        self.ButtonRoboterStop.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonRoboterStart = QPushButton(self.Roboter)
        self.ButtonRoboterStart.setObjectName(u"ButtonRoboterStart")
        self.ButtonRoboterStart.setGeometry(QRect(140, 70, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterStart.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterStart.setSizePolicy(sizePolicy)
        self.ButtonRoboterStart.setMinimumSize(QSize(300, 0))
        self.ButtonRoboterStart.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterStart.setFont(font1)
        self.ButtonRoboterStart.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonStopRPCServer = QPushButton(self.Roboter)
        self.ButtonStopRPCServer.setObjectName(u"ButtonStopRPCServer")
        self.ButtonStopRPCServer.setGeometry(QRect(830, 220, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonStopRPCServer.sizePolicy().hasHeightForWidth())
        self.ButtonStopRPCServer.setSizePolicy(sizePolicy)
        self.ButtonStopRPCServer.setMaximumSize(QSize(350, 16777215))
        self.ButtonStopRPCServer.setFont(font1)
        self.ButtonStopRPCServer.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonRoboterPause = QPushButton(self.Roboter)
        self.ButtonRoboterPause.setObjectName(u"ButtonRoboterPause")
        self.ButtonRoboterPause.setGeometry(QRect(140, 220, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterPause.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterPause.setSizePolicy(sizePolicy)
        self.ButtonRoboterPause.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterPause.setFont(font1)
        self.ButtonRoboterPause.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.addTab(self.Roboter, "")
        self.ImageSzaidelLogoBig.raise_()
        self.ButtonZurueck.raise_()
        self.ButtonRoboterPause.raise_()
        self.ButtonRoboterStart.raise_()
        self.ButtonRoboterStop.raise_()
        self.ButtonStopRPCServer.raise_()
        self.Aufnahme = QWidget()
        self.Aufnahme.setObjectName(u"Aufnahme")
        self.ButtonZurueck_2 = QPushButton(self.Aufnahme)
        self.ButtonZurueck_2.setObjectName(u"ButtonZurueck_2")
        self.ButtonZurueck_2.setGeometry(QRect(0, 140, 81, 81))
        self.ButtonZurueck_2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonZurueck_2.setIcon(icon2)
        self.ButtonZurueck_2.setIconSize(QSize(81, 81))
        self.ButtonZurueck_2.setFlat(True)
        self.ImageAufnahmePos = QLabel(self.Aufnahme)
        self.ImageAufnahmePos.setObjectName(u"ImageAufnahmePos")
        self.ImageAufnahmePos.setGeometry(QRect(110, 40, 390, 270))
        self.ImageAufnahmePos.setFrameShape(QFrame.Shape.Box)
        self.ImageAufnahmePos.setPixmap(QPixmap(u":/Aufnahme/imgs/Aufnahmepos.png"))
        self.ImageAufnahmePos.setScaledContents(True)
        self.label_5 = QLabel(self.Aufnahme)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(550, 60, 411, 31))
        self.label_5.setFont(font1)
        self.label_5.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.label_6 = QLabel(self.Aufnahme)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(550, 160, 411, 31))
        self.label_6.setFont(font1)
        self.label_6.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.EingabeVerschiebungX = QSpinBox(self.Aufnahme)
        self.EingabeVerschiebungX.setObjectName(u"EingabeVerschiebungX")
        self.EingabeVerschiebungX.setGeometry(QRect(970, 60, 141, 41))
        self.EingabeVerschiebungX.setMinimum(-20)
        self.EingabeVerschiebungX.setMaximum(20)
        self.EingabeVerschiebungY = QSpinBox(self.Aufnahme)
        self.EingabeVerschiebungY.setObjectName(u"EingabeVerschiebungY")
        self.EingabeVerschiebungY.setGeometry(QRect(970, 160, 141, 41))
        self.EingabeVerschiebungY.setMinimum(-20)
        self.EingabeVerschiebungY.setMaximum(20)
        self.ButtonDatenSenden_2 = QPushButton(self.Aufnahme)
        self.ButtonDatenSenden_2.setObjectName(u"ButtonDatenSenden_2")
        self.ButtonDatenSenden_2.setGeometry(QRect(540, 250, 571, 91))
        self.ButtonDatenSenden_2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.tabWidget.addTab(self.Aufnahme, "")
        self.stackedWidget.addWidget(self.RoboParameter)
        self.Settings = QWidget()
        self.Settings.setObjectName(u"Settings")
        self.tabWidget_2 = QTabWidget(self.Settings)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 1280, 390))
        self.PallettiererSpezifisch = QWidget()
        self.PallettiererSpezifisch.setObjectName(u"PallettiererSpezifisch")
        self.ButtonZurueck_3 = QPushButton(self.PallettiererSpezifisch)
        self.ButtonZurueck_3.setObjectName(u"ButtonZurueck_3")
        self.ButtonZurueck_3.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_3.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonZurueck_3.setIcon(icon2)
        self.ButtonZurueck_3.setIconSize(QSize(81, 81))
        self.ButtonZurueck_3.setFlat(True)
        self.formLayoutWidget = QWidget(self.PallettiererSpezifisch)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(100, 10, 551, 341))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.formLayoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label_11)

        self.lineEditURModel = QLineEdit(self.formLayoutWidget)
        self.lineEditURModel.setObjectName(u"lineEditURModel")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.lineEditURModel)

        self.label_12 = QLabel(self.formLayoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_12)

        self.lineEditURSerialNo = QLineEdit(self.formLayoutWidget)
        self.lineEditURSerialNo.setObjectName(u"lineEditURSerialNo")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.lineEditURSerialNo)

        self.label_13 = QLabel(self.formLayoutWidget)
        self.label_13.setObjectName(u"label_13")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_13)

        self.lineEditURManufacturingDate = QLineEdit(self.formLayoutWidget)
        self.lineEditURManufacturingDate.setObjectName(u"lineEditURManufacturingDate")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.lineEditURManufacturingDate)

        self.label_14 = QLabel(self.formLayoutWidget)
        self.label_14.setObjectName(u"label_14")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_14)

        self.lineEditURSoftwareVer = QLineEdit(self.formLayoutWidget)
        self.lineEditURSoftwareVer.setObjectName(u"lineEditURSoftwareVer")

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.lineEditURSoftwareVer)

        self.label_15 = QLabel(self.formLayoutWidget)
        self.label_15.setObjectName(u"label_15")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.label_15)

        self.lineEditURName = QLineEdit(self.formLayoutWidget)
        self.lineEditURName.setObjectName(u"lineEditURName")

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.lineEditURName)

        self.label_16 = QLabel(self.formLayoutWidget)
        self.label_16.setObjectName(u"label_16")

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.label_16)

        self.lineEditURStandort = QLineEdit(self.formLayoutWidget)
        self.lineEditURStandort.setObjectName(u"lineEditURStandort")

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.lineEditURStandort)

        self.label_17 = QLabel(self.formLayoutWidget)
        self.label_17.setObjectName(u"label_17")

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.label_17)

        self.lineEditNumberPlans = QLineEdit(self.formLayoutWidget)
        self.lineEditNumberPlans.setObjectName(u"lineEditNumberPlans")
        self.lineEditNumberPlans.setEnabled(False)

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.lineEditNumberPlans)

        self.label_18 = QLabel(self.formLayoutWidget)
        self.label_18.setObjectName(u"label_18")

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.label_18)

        self.lineEditNumberCycles = QLineEdit(self.formLayoutWidget)
        self.lineEditNumberCycles.setObjectName(u"lineEditNumberCycles")
        self.lineEditNumberCycles.setEnabled(False)

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.lineEditNumberCycles)

        self.label_19 = QLabel(self.formLayoutWidget)
        self.label_19.setObjectName(u"label_19")

        self.formLayout.setWidget(8, QFormLayout.LabelRole, self.label_19)

        self.lineEditLastRestart = QLineEdit(self.formLayoutWidget)
        self.lineEditLastRestart.setObjectName(u"lineEditLastRestart")
        self.lineEditLastRestart.setEnabled(False)

        self.formLayout.setWidget(8, QFormLayout.FieldRole, self.lineEditLastRestart)

        self.formLayoutWidget_2 = QWidget(self.PallettiererSpezifisch)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(690, 10, 551, 341))
        self.formLayout_2 = QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_20 = QLabel(self.formLayoutWidget_2)
        self.label_20.setObjectName(u"label_20")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label_20)

        self.lineEditDisplayModel = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayModel.setObjectName(u"lineEditDisplayModel")

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.lineEditDisplayModel)

        self.label_21 = QLabel(self.formLayoutWidget_2)
        self.label_21.setObjectName(u"label_21")

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.label_21)

        self.lineEditDisplayRefreshRate = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayRefreshRate.setObjectName(u"lineEditDisplayRefreshRate")
        self.lineEditDisplayRefreshRate.setEnabled(False)

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.lineEditDisplayRefreshRate)

        self.label_22 = QLabel(self.formLayoutWidget_2)
        self.label_22.setObjectName(u"label_22")

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.label_22)

        self.lineEditDisplayWidth = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayWidth.setObjectName(u"lineEditDisplayWidth")
        self.lineEditDisplayWidth.setEnabled(False)

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.lineEditDisplayWidth)

        self.label_23 = QLabel(self.formLayoutWidget_2)
        self.label_23.setObjectName(u"label_23")

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.label_23)

        self.lineEditDisplayHeight = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayHeight.setObjectName(u"lineEditDisplayHeight")
        self.lineEditDisplayHeight.setEnabled(False)

        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.lineEditDisplayHeight)

        self.pushButtonSpeichern = QPushButton(self.PallettiererSpezifisch)
        self.pushButtonSpeichern.setObjectName(u"pushButtonSpeichern")
        self.pushButtonSpeichern.setGeometry(QRect(4, 15, 91, 24))
        self.tabWidget_2.addTab(self.PallettiererSpezifisch, "")
        self.adminSettingsTab = QWidget()
        self.adminSettingsTab.setObjectName(u"adminSettingsTab")
        self.ButtonZurueck_4 = QPushButton(self.adminSettingsTab)
        self.ButtonZurueck_4.setObjectName(u"ButtonZurueck_4")
        self.ButtonZurueck_4.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_4.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonZurueck_4.setIcon(icon2)
        self.ButtonZurueck_4.setIconSize(QSize(81, 81))
        self.ButtonZurueck_4.setFlat(True)
        self.formLayoutWidget_3 = QWidget(self.adminSettingsTab)
        self.formLayoutWidget_3.setObjectName(u"formLayoutWidget_3")
        self.formLayoutWidget_3.setGeometry(QRect(100, 10, 551, 341))
        self.formLayout_3 = QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.passwordEdit = QLineEdit(self.formLayoutWidget_3)
        self.passwordEdit.setObjectName(u"passwordEdit")

        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.passwordEdit)

        self.label_8 = QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName(u"label_8")

        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.label_8)

        self.formLayoutWidget_4 = QWidget(self.adminSettingsTab)
        self.formLayoutWidget_4.setObjectName(u"formLayoutWidget_4")
        self.formLayoutWidget_4.setGeometry(QRect(690, 10, 551, 341))
        self.formLayout_4 = QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName(u"formLayout_4")
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushButtonSpeichern_2 = QPushButton(self.adminSettingsTab)
        self.pushButtonSpeichern_2.setObjectName(u"pushButtonSpeichern_2")
        self.pushButtonSpeichern_2.setGeometry(QRect(4, 15, 91, 24))
        self.tabWidget_2.addTab(self.adminSettingsTab, "")
        self.editorSettingsTab = QWidget()
        self.editorSettingsTab.setObjectName(u"editorSettingsTab")
        self.ButtonZurueck_5 = QPushButton(self.editorSettingsTab)
        self.ButtonZurueck_5.setObjectName(u"ButtonZurueck_5")
        self.ButtonZurueck_5.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_5.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonZurueck_5.setIcon(icon2)
        self.ButtonZurueck_5.setIconSize(QSize(81, 81))
        self.ButtonZurueck_5.setFlat(True)
        self.pushButtonSpeichern_3 = QPushButton(self.editorSettingsTab)
        self.pushButtonSpeichern_3.setObjectName(u"pushButtonSpeichern_3")
        self.pushButtonSpeichern_3.setGeometry(QRect(4, 15, 91, 24))
        self.tabWidget_2.addTab(self.editorSettingsTab, "")
        self.explorerSettingsTab = QWidget()
        self.explorerSettingsTab.setObjectName(u"explorerSettingsTab")
        self.ButtonZurueck_6 = QPushButton(self.explorerSettingsTab)
        self.ButtonZurueck_6.setObjectName(u"ButtonZurueck_6")
        self.ButtonZurueck_6.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_6.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.ButtonZurueck_6.setIcon(icon2)
        self.ButtonZurueck_6.setIconSize(QSize(81, 81))
        self.ButtonZurueck_6.setFlat(True)
        self.pushButtonSpeichern_4 = QPushButton(self.explorerSettingsTab)
        self.pushButtonSpeichern_4.setObjectName(u"pushButtonSpeichern_4")
        self.pushButtonSpeichern_4.setGeometry(QRect(4, 15, 91, 24))
        self.tabWidget_2.addTab(self.explorerSettingsTab, "")
        self.stackedWidget.addWidget(self.Settings)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(2)
        self.ButtonSettings.setDefault(False)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Palletierer", None))
        self.ButtonSettings.setText("")
        self.checkBoxEinzelpaket.setText(QCoreApplication.translate("Form", u"Einzelpaket", None))
        self.ButtonDatenSenden.setText(QCoreApplication.translate("Form", u"Daten Senden", None))
        self.ButtonOpenParameterRoboter.setText(QCoreApplication.translate("Form", u"Parameter Roboter", None))
        self.label_7.setText("")
        self.LabelPalletenplanInfo.setText(QCoreApplication.translate("Form", u"Kein Pallettenplan geladen", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>mm</p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>kg</p></body></html>", None))
        self.EingabePallettenplan.setPlaceholderText(QCoreApplication.translate("Form", u"z.B: 699-00120", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Gewicht: </p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Palletierplan: </p></body></html>", None))
        self.LadePallettenplan.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Startlage: </p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Kartonh\u00f6he: </p></body></html>", None))
        self.ButtonZurueck.setText("")
        self.ImageSzaidelLogoBig.setText("")
        self.ButtonRoboterStop.setText(QCoreApplication.translate("Form", u"Roboter Stop", None))
        self.ButtonRoboterStart.setText(QCoreApplication.translate("Form", u"Roboter Start", None))
        self.ButtonStopRPCServer.setText(QCoreApplication.translate("Form", u"Stop RPC Server", None))
        self.ButtonRoboterPause.setText(QCoreApplication.translate("Form", u"Roboter Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Roboter), QCoreApplication.translate("Form", u"Roboter", None))
        self.ButtonZurueck_2.setText("")
        self.ImageAufnahmePos.setText("")
#if QT_CONFIG(whatsthis)
        self.label_5.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Gibt die Verschiebung in Richtung x an.</p><p>min. -20mm</p><p>max.  20mm</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_5.setText(QCoreApplication.translate("Form", u"verschieben in Richtung x von:", None))
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Gibt die Verschiebung in Richtung y an.</p><p>min. -20mm</p><p>max. 20mm</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_6.setText(QCoreApplication.translate("Form", u"verschieben in Richtung y von:", None))
        self.EingabeVerschiebungX.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.EingabeVerschiebungY.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.ButtonDatenSenden_2.setText(QCoreApplication.translate("Form", u"Daten senden", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Aufnahme), QCoreApplication.translate("Form", u"Aufnahme", None))
        self.ButtonZurueck_3.setText("")
        self.label_11.setText(QCoreApplication.translate("Form", u"UR Model: ", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"UR Serial #: ", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"UR Manufacturing Date: ", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"UR Software Ver.: ", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Pallettierer Name: ", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Pallettierer Standort: ", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Number of Plans: ", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Number of use cycles: ", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"last restart: ", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Display Model: ", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"Refresh rate: ", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"Display width: ", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Display height", None))
        self.pushButtonSpeichern.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.PallettiererSpezifisch), QCoreApplication.translate("Form", u"Info", None))
        self.ButtonZurueck_4.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"Passwort: ", None))
        self.pushButtonSpeichern_2.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.adminSettingsTab), QCoreApplication.translate("Form", u"Admin", None))
        self.ButtonZurueck_5.setText("")
        self.pushButtonSpeichern_3.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.editorSettingsTab), QCoreApplication.translate("Form", u"Editor", None))
        self.ButtonZurueck_6.setText("")
        self.pushButtonSpeichern_4.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.explorerSettingsTab), QCoreApplication.translate("Form", u"Explorer", None))
    # retranslateUi

