# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QFrame, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QPushButton,
    QSizePolicy, QSpinBox, QStackedWidget, QTabWidget,
    QTextEdit, QToolButton, QTreeView, QWidget)
from . import MainWindowResources_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setWindowModality(Qt.NonModal)
        Form.resize(1280, 720)
        Form.setMinimumSize(QSize(1280, 720))
        Form.setMaximumSize(QSize(1280, 720))
        palette = QPalette()
        brush = QBrush(QColor(85, 85, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Active, QPalette.Link, brush)
        palette.setBrush(QPalette.Active, QPalette.Accent, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush)
        Form.setPalette(palette)
        font = QFont()
        font.setFamilies([u"RobotoMono Nerd Font"])
        font.setPointSize(11)
        Form.setFont(font)
        Form.setCursor(QCursor(Qt.ArrowCursor))
        Form.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u"pallet.ico", QSize(), QIcon.Normal, QIcon.On)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(True)
        Form.setLocale(QLocale(QLocale.German, QLocale.Germany))
        Form.setInputMethodHints(Qt.ImhNone)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QRect(0, 0, 1280, 711))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setLayoutDirection(Qt.LeftToRight)
        self.stackedWidget.setLocale(QLocale(QLocale.German, QLocale.Germany))
        self.stackedWidget.setFrameShape(QFrame.NoFrame)
        self.MainMenu = QWidget()
        self.MainMenu.setObjectName(u"MainMenu")
        self.ButtonSettings = QPushButton(self.MainMenu)
        self.ButtonSettings.setObjectName(u"ButtonSettings")
        self.ButtonSettings.setGeometry(QRect(0, 0, 61, 61))
        sizePolicy.setHeightForWidth(self.ButtonSettings.sizePolicy().hasHeightForWidth())
        self.ButtonSettings.setSizePolicy(sizePolicy)
        self.ButtonSettings.setAutoFillBackground(False)
        self.ButtonSettings.setFlat(True)
        self.checkBoxEinzelpaket = QCheckBox(self.MainMenu)
        self.checkBoxEinzelpaket.setObjectName(u"checkBoxEinzelpaket")
        self.checkBoxEinzelpaket.setEnabled(False)
        self.checkBoxEinzelpaket.setGeometry(QRect(70, 310, 251, 61))
        font1 = QFont()
        font1.setFamilies([u"RobotoMono Nerd Font"])
        font1.setPointSize(16)
        self.checkBoxEinzelpaket.setFont(font1)
        self.checkBoxEinzelpaket.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBoxEinzelpaket.setLayoutDirection(Qt.RightToLeft)
        self.ButtonDatenSenden = QPushButton(self.MainMenu)
        self.ButtonDatenSenden.setObjectName(u"ButtonDatenSenden")
        self.ButtonDatenSenden.setEnabled(False)
        self.ButtonDatenSenden.setGeometry(QRect(610, 310, 261, 61))
        self.ButtonDatenSenden.setFont(font1)
        self.ButtonDatenSenden.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonOpenParameterRoboter = QPushButton(self.MainMenu)
        self.ButtonOpenParameterRoboter.setObjectName(u"ButtonOpenParameterRoboter")
        self.ButtonOpenParameterRoboter.setEnabled(False)
        self.ButtonOpenParameterRoboter.setGeometry(QRect(330, 310, 261, 61))
        self.ButtonOpenParameterRoboter.setFont(font1)
        self.ButtonOpenParameterRoboter.setCursor(QCursor(Qt.PointingHandCursor))
        self.label_7 = QLabel(self.MainMenu)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(940, 90, 271, 271))
        self.label_7.setPixmap(QPixmap(u":/Szaidel Logo/imgs/szaidel-transparent.png"))
        self.label_7.setScaledContents(True)
        self.LabelPalletenplanInfo = QLabel(self.MainMenu)
        self.LabelPalletenplanInfo.setObjectName(u"LabelPalletenplanInfo")
        self.LabelPalletenplanInfo.setGeometry(QRect(60, 0, 1161, 51))
        font2 = QFont()
        font2.setFamilies([u"RobotoMono Nerd Font"])
        font2.setPointSize(18)
        font2.setUnderline(False)
        font2.setKerning(True)
        self.LabelPalletenplanInfo.setFont(font2)
        self.LabelPalletenplanInfo.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.MainMenu)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(790, 200, 121, 41))
        self.label_9.setFont(font1)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_10 = QLabel(self.MainMenu)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(790, 250, 121, 41))
        self.label_10.setFont(font1)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.EingabePallettenplan = QLineEdit(self.MainMenu)
        self.EingabePallettenplan.setObjectName(u"EingabePallettenplan")
        self.EingabePallettenplan.setGeometry(QRect(322, 90, 461, 39))
        self.EingabePallettenplan.setMinimumSize(QSize(0, 39))
        self.EingabePallettenplan.setMaximumSize(QSize(16777215, 39))
        self.EingabePallettenplan.setFont(font1)
        self.EingabePallettenplan.setInputMethodHints(Qt.ImhPreferNumbers)
        self.label_4 = QLabel(self.MainMenu)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 248, 241, 41))
        self.label_4.setFont(font1)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label = QLabel(self.MainMenu)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 90, 241, 41))
        self.label.setFont(font1)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.LadePallettenplan = QPushButton(self.MainMenu)
        self.LadePallettenplan.setObjectName(u"LadePallettenplan")
        self.LadePallettenplan.setGeometry(QRect(795, 80, 60, 60))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.LadePallettenplan.sizePolicy().hasHeightForWidth())
        self.LadePallettenplan.setSizePolicy(sizePolicy1)
        self.LadePallettenplan.setCursor(QCursor(Qt.PointingHandCursor))
        self.LadePallettenplan.setFocusPolicy(Qt.StrongFocus)
        icon1 = QIcon()
        icon1.addFile(u":/Misc/imgs/load.png", QSize(), QIcon.Normal, QIcon.Off)
        self.LadePallettenplan.setIcon(icon1)
        self.LadePallettenplan.setIconSize(QSize(60, 60))
        self.LadePallettenplan.setFlat(True)
        self.label_2 = QLabel(self.MainMenu)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 140, 241, 41))
        self.label_2.setFont(font1)
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.EingabeStartlage = QSpinBox(self.MainMenu)
        self.EingabeStartlage.setObjectName(u"EingabeStartlage")
        self.EingabeStartlage.setEnabled(False)
        self.EingabeStartlage.setGeometry(QRect(322, 144, 461, 39))
        sizePolicy1.setHeightForWidth(self.EingabeStartlage.sizePolicy().hasHeightForWidth())
        self.EingabeStartlage.setSizePolicy(sizePolicy1)
        self.EingabeStartlage.setMinimumSize(QSize(0, 39))
        self.EingabeStartlage.setMaximumSize(QSize(16777215, 39))
        self.EingabeStartlage.setFont(font1)
        self.EingabeStartlage.setCursor(QCursor(Qt.IBeamCursor))
        self.EingabeStartlage.setMinimum(1)
        self.EingabeStartlage.setValue(1)
        self.label_3 = QLabel(self.MainMenu)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 194, 241, 41))
        self.label_3.setFont(font1)
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.EingabeKartonGewicht = QLineEdit(self.MainMenu)
        self.EingabeKartonGewicht.setObjectName(u"EingabeKartonGewicht")
        self.EingabeKartonGewicht.setEnabled(False)
        self.EingabeKartonGewicht.setGeometry(QRect(322, 252, 461, 39))
        self.EingabeKartonGewicht.setMinimumSize(QSize(0, 39))
        self.EingabeKartonGewicht.setFont(font1)
        self.EingabeKartonGewicht.setInputMethodHints(Qt.ImhDigitsOnly|Qt.ImhFormattedNumbersOnly)
        self.EingabeKartonhoehe = QLineEdit(self.MainMenu)
        self.EingabeKartonhoehe.setObjectName(u"EingabeKartonhoehe")
        self.EingabeKartonhoehe.setEnabled(False)
        self.EingabeKartonhoehe.setGeometry(QRect(322, 198, 461, 39))
        self.EingabeKartonhoehe.setMinimumSize(QSize(0, 39))
        self.EingabeKartonhoehe.setMaximumSize(QSize(16777215, 39))
        self.EingabeKartonhoehe.setFont(font1)
        self.EingabeKartonhoehe.setInputMethodHints(Qt.ImhDigitsOnly)
        self.EingabeKartonhoehe.setClearButtonEnabled(False)
        self.line = QFrame(self.MainMenu)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 50, 1281, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.pushButtonVolumeOnOff = QPushButton(self.MainMenu)
        self.pushButtonVolumeOnOff.setObjectName(u"pushButtonVolumeOnOff")
        self.pushButtonVolumeOnOff.setGeometry(QRect(1221, -1, 60, 60))
        icon2 = QIcon()
        icon2.addFile(u":/Sound/imgs/volume-on.png", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/Sound/imgs/volume-off.png", QSize(), QIcon.Normal, QIcon.On)
        self.pushButtonVolumeOnOff.setIcon(icon2)
        self.pushButtonVolumeOnOff.setIconSize(QSize(50, 50))
        self.pushButtonVolumeOnOff.setCheckable(False)
        self.pushButtonVolumeOnOff.setChecked(False)
        self.pushButtonVolumeOnOff.setFlat(True)
        self.startaudio = QPushButton(self.MainMenu)
        self.startaudio.setObjectName(u"startaudio")
        self.startaudio.setGeometry(QRect(170, 470, 75, 24))
        self.stopaudio = QPushButton(self.MainMenu)
        self.stopaudio.setObjectName(u"stopaudio")
        self.stopaudio.setGeometry(QRect(260, 470, 75, 24))
        self.openExperimentalTab = QPushButton(self.MainMenu)
        self.openExperimentalTab.setObjectName(u"openExperimentalTab")
        self.openExperimentalTab.setGeometry(QRect(1150, 660, 121, 41))
        self.stackedWidget.addWidget(self.MainMenu)
        self.checkBoxEinzelpaket.raise_()
        self.ButtonDatenSenden.raise_()
        self.ButtonOpenParameterRoboter.raise_()
        self.label_7.raise_()
        self.LabelPalletenplanInfo.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.EingabePallettenplan.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.LadePallettenplan.raise_()
        self.label_2.raise_()
        self.EingabeStartlage.raise_()
        self.label_3.raise_()
        self.EingabeKartonGewicht.raise_()
        self.EingabeKartonhoehe.raise_()
        self.line.raise_()
        self.startaudio.raise_()
        self.stopaudio.raise_()
        self.ButtonSettings.raise_()
        self.pushButtonVolumeOnOff.raise_()
        self.openExperimentalTab.raise_()
        self.RoboParameter = QWidget()
        self.RoboParameter.setObjectName(u"RoboParameter")
        self.tabWidget = QTabWidget(self.RoboParameter)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1280, 711))
        self.tabWidget.setFont(font1)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.Roboter = QWidget()
        self.Roboter.setObjectName(u"Roboter")
        self.ButtonZurueck = QPushButton(self.Roboter)
        self.ButtonZurueck.setObjectName(u"ButtonZurueck")
        self.ButtonZurueck.setGeometry(QRect(0, 140, 81, 81))
        self.ButtonZurueck.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/Misc/imgs/zurueck.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ButtonZurueck.setIcon(icon3)
        self.ButtonZurueck.setIconSize(QSize(81, 81))
        self.ButtonZurueck.setFlat(True)
        self.ImageSzaidelLogoBig = QLabel(self.Roboter)
        self.ImageSzaidelLogoBig.setObjectName(u"ImageSzaidelLogoBig")
        self.ImageSzaidelLogoBig.setGeometry(QRect(360, -35, 600, 337))
        self.ImageSzaidelLogoBig.setSizeIncrement(QSize(0, 0))
        self.ImageSzaidelLogoBig.setPixmap(QPixmap(u":/Szaidel Logo/imgs/logoszaidel-transparent-big.png"))
        self.ImageSzaidelLogoBig.setScaledContents(True)
        self.ImageSzaidelLogoBig.setTextInteractionFlags(Qt.NoTextInteraction)
        self.ButtonRoboterStop = QPushButton(self.Roboter)
        self.ButtonRoboterStop.setObjectName(u"ButtonRoboterStop")
        self.ButtonRoboterStop.setEnabled(False)
        self.ButtonRoboterStop.setGeometry(QRect(830, 70, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterStop.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterStop.setSizePolicy(sizePolicy)
        self.ButtonRoboterStop.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterStop.setFont(font1)
        self.ButtonRoboterStop.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonRoboterStart = QPushButton(self.Roboter)
        self.ButtonRoboterStart.setObjectName(u"ButtonRoboterStart")
        self.ButtonRoboterStart.setEnabled(False)
        self.ButtonRoboterStart.setGeometry(QRect(140, 70, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterStart.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterStart.setSizePolicy(sizePolicy)
        self.ButtonRoboterStart.setMinimumSize(QSize(300, 0))
        self.ButtonRoboterStart.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterStart.setFont(font1)
        self.ButtonRoboterStart.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonStopRPCServer = QPushButton(self.Roboter)
        self.ButtonStopRPCServer.setObjectName(u"ButtonStopRPCServer")
        self.ButtonStopRPCServer.setEnabled(False)
        self.ButtonStopRPCServer.setGeometry(QRect(830, 220, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonStopRPCServer.sizePolicy().hasHeightForWidth())
        self.ButtonStopRPCServer.setSizePolicy(sizePolicy)
        self.ButtonStopRPCServer.setMaximumSize(QSize(350, 16777215))
        self.ButtonStopRPCServer.setFont(font1)
        self.ButtonStopRPCServer.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonRoboterPause = QPushButton(self.Roboter)
        self.ButtonRoboterPause.setObjectName(u"ButtonRoboterPause")
        self.ButtonRoboterPause.setEnabled(False)
        self.ButtonRoboterPause.setGeometry(QRect(140, 220, 341, 71))
        sizePolicy.setHeightForWidth(self.ButtonRoboterPause.sizePolicy().hasHeightForWidth())
        self.ButtonRoboterPause.setSizePolicy(sizePolicy)
        self.ButtonRoboterPause.setMaximumSize(QSize(350, 16777215))
        self.ButtonRoboterPause.setFont(font1)
        self.ButtonRoboterPause.setCursor(QCursor(Qt.PointingHandCursor))
        self.tabWidget.addTab(self.Roboter, "")
        self.ImageSzaidelLogoBig.raise_()
        self.ButtonZurueck.raise_()
        self.ButtonRoboterPause.raise_()
        self.ButtonRoboterStart.raise_()
        self.ButtonRoboterStop.raise_()
        self.ButtonStopRPCServer.raise_()
        self.Aufnahme = QWidget()
        self.Aufnahme.setObjectName(u"Aufnahme")
        self.ButtonZurueck_2 = QPushButton(self.Aufnahme)
        self.ButtonZurueck_2.setObjectName(u"ButtonZurueck_2")
        self.ButtonZurueck_2.setGeometry(QRect(0, 140, 81, 81))
        self.ButtonZurueck_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_2.setIcon(icon3)
        self.ButtonZurueck_2.setIconSize(QSize(81, 81))
        self.ButtonZurueck_2.setFlat(True)
        self.ImageAufnahmePos = QLabel(self.Aufnahme)
        self.ImageAufnahmePos.setObjectName(u"ImageAufnahmePos")
        self.ImageAufnahmePos.setGeometry(QRect(110, 40, 390, 270))
        self.ImageAufnahmePos.setFrameShape(QFrame.Box)
        self.ImageAufnahmePos.setPixmap(QPixmap(u":/Aufnahme/imgs/Aufnahmepos.png"))
        self.ImageAufnahmePos.setScaledContents(True)
        self.label_5 = QLabel(self.Aufnahme)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(550, 60, 411, 31))
        self.label_5.setFont(font1)
        self.label_5.setCursor(QCursor(Qt.ArrowCursor))
        self.label_6 = QLabel(self.Aufnahme)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(550, 160, 411, 31))
        self.label_6.setFont(font1)
        self.label_6.setCursor(QCursor(Qt.ArrowCursor))
        self.EingabeVerschiebungX = QSpinBox(self.Aufnahme)
        self.EingabeVerschiebungX.setObjectName(u"EingabeVerschiebungX")
        self.EingabeVerschiebungX.setGeometry(QRect(970, 60, 141, 41))
        self.EingabeVerschiebungX.setMinimum(-20)
        self.EingabeVerschiebungX.setMaximum(20)
        self.EingabeVerschiebungY = QSpinBox(self.Aufnahme)
        self.EingabeVerschiebungY.setObjectName(u"EingabeVerschiebungY")
        self.EingabeVerschiebungY.setGeometry(QRect(970, 160, 141, 41))
        self.EingabeVerschiebungY.setMinimum(-20)
        self.EingabeVerschiebungY.setMaximum(20)
        self.ButtonDatenSenden_2 = QPushButton(self.Aufnahme)
        self.ButtonDatenSenden_2.setObjectName(u"ButtonDatenSenden_2")
        self.ButtonDatenSenden_2.setGeometry(QRect(540, 250, 571, 91))
        self.ButtonDatenSenden_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.tabWidget.addTab(self.Aufnahme, "")
        self.stackedWidget.addWidget(self.RoboParameter)
        self.Settings = QWidget()
        self.Settings.setObjectName(u"Settings")
        self.tabWidget_2 = QTabWidget(self.Settings)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 1280, 390))
        self.PallettiererSpezifisch = QWidget()
        self.PallettiererSpezifisch.setObjectName(u"PallettiererSpezifisch")
        self.ButtonZurueck_3 = QPushButton(self.PallettiererSpezifisch)
        self.ButtonZurueck_3.setObjectName(u"ButtonZurueck_3")
        self.ButtonZurueck_3.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_3.setIcon(icon3)
        self.ButtonZurueck_3.setIconSize(QSize(81, 81))
        self.ButtonZurueck_3.setFlat(True)
        self.formLayoutWidget = QWidget(self.PallettiererSpezifisch)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(100, 10, 551, 341))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.formLayoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label_11)

        self.label_12 = QLabel(self.formLayoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.label_12)

        self.lineEditURSerialNo = QLineEdit(self.formLayoutWidget)
        self.lineEditURSerialNo.setObjectName(u"lineEditURSerialNo")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.lineEditURSerialNo)

        self.label_13 = QLabel(self.formLayoutWidget)
        self.label_13.setObjectName(u"label_13")

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.label_13)

        self.lineEditURManufacturingDate = QLineEdit(self.formLayoutWidget)
        self.lineEditURManufacturingDate.setObjectName(u"lineEditURManufacturingDate")

        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.lineEditURManufacturingDate)

        self.label_14 = QLabel(self.formLayoutWidget)
        self.label_14.setObjectName(u"label_14")

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.label_14)

        self.lineEditURSoftwareVer = QLineEdit(self.formLayoutWidget)
        self.lineEditURSoftwareVer.setObjectName(u"lineEditURSoftwareVer")

        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.lineEditURSoftwareVer)

        self.label_15 = QLabel(self.formLayoutWidget)
        self.label_15.setObjectName(u"label_15")

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.label_15)

        self.lineEditURName = QLineEdit(self.formLayoutWidget)
        self.lineEditURName.setObjectName(u"lineEditURName")

        self.formLayout.setWidget(4, QFormLayout.FieldRole, self.lineEditURName)

        self.label_16 = QLabel(self.formLayoutWidget)
        self.label_16.setObjectName(u"label_16")

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.label_16)

        self.lineEditURStandort = QLineEdit(self.formLayoutWidget)
        self.lineEditURStandort.setObjectName(u"lineEditURStandort")

        self.formLayout.setWidget(5, QFormLayout.FieldRole, self.lineEditURStandort)

        self.label_17 = QLabel(self.formLayoutWidget)
        self.label_17.setObjectName(u"label_17")

        self.formLayout.setWidget(6, QFormLayout.LabelRole, self.label_17)

        self.lineEditNumberPlans = QLineEdit(self.formLayoutWidget)
        self.lineEditNumberPlans.setObjectName(u"lineEditNumberPlans")
        self.lineEditNumberPlans.setEnabled(False)

        self.formLayout.setWidget(6, QFormLayout.FieldRole, self.lineEditNumberPlans)

        self.label_18 = QLabel(self.formLayoutWidget)
        self.label_18.setObjectName(u"label_18")

        self.formLayout.setWidget(7, QFormLayout.LabelRole, self.label_18)

        self.lineEditNumberCycles = QLineEdit(self.formLayoutWidget)
        self.lineEditNumberCycles.setObjectName(u"lineEditNumberCycles")
        self.lineEditNumberCycles.setEnabled(False)

        self.formLayout.setWidget(7, QFormLayout.FieldRole, self.lineEditNumberCycles)

        self.label_19 = QLabel(self.formLayoutWidget)
        self.label_19.setObjectName(u"label_19")

        self.formLayout.setWidget(8, QFormLayout.LabelRole, self.label_19)

        self.lineEditLastRestart = QLineEdit(self.formLayoutWidget)
        self.lineEditLastRestart.setObjectName(u"lineEditLastRestart")
        self.lineEditLastRestart.setEnabled(False)

        self.formLayout.setWidget(8, QFormLayout.FieldRole, self.lineEditLastRestart)

        self.comboBoxChooseURModel = QComboBox(self.formLayoutWidget)
        self.comboBoxChooseURModel.addItem("")
        self.comboBoxChooseURModel.addItem("")
        self.comboBoxChooseURModel.setObjectName(u"comboBoxChooseURModel")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.comboBoxChooseURModel)

        self.formLayoutWidget_2 = QWidget(self.PallettiererSpezifisch)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(690, 10, 551, 341))
        self.formLayout_2 = QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setLabelAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_20 = QLabel(self.formLayoutWidget_2)
        self.label_20.setObjectName(u"label_20")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label_20)

        self.lineEditDisplayModel = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayModel.setObjectName(u"lineEditDisplayModel")

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.lineEditDisplayModel)

        self.label_21 = QLabel(self.formLayoutWidget_2)
        self.label_21.setObjectName(u"label_21")

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.label_21)

        self.lineEditDisplayRefreshRate = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayRefreshRate.setObjectName(u"lineEditDisplayRefreshRate")
        self.lineEditDisplayRefreshRate.setEnabled(False)

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.lineEditDisplayRefreshRate)

        self.label_22 = QLabel(self.formLayoutWidget_2)
        self.label_22.setObjectName(u"label_22")

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.label_22)

        self.lineEditDisplayWidth = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayWidth.setObjectName(u"lineEditDisplayWidth")
        self.lineEditDisplayWidth.setEnabled(False)

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.lineEditDisplayWidth)

        self.label_23 = QLabel(self.formLayoutWidget_2)
        self.label_23.setObjectName(u"label_23")

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.label_23)

        self.lineEditDisplayHeight = QLineEdit(self.formLayoutWidget_2)
        self.lineEditDisplayHeight.setObjectName(u"lineEditDisplayHeight")
        self.lineEditDisplayHeight.setEnabled(False)

        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.lineEditDisplayHeight)

        self.pushButtonSpeichern = QPushButton(self.PallettiererSpezifisch)
        self.pushButtonSpeichern.setObjectName(u"pushButtonSpeichern")
        self.pushButtonSpeichern.setGeometry(QRect(4, 15, 91, 24))
        self.pushButtonSearchUpdate = QPushButton(self.PallettiererSpezifisch)
        self.pushButtonSearchUpdate.setObjectName(u"pushButtonSearchUpdate")
        self.pushButtonSearchUpdate.setGeometry(QRect(1010, 220, 152, 81))
        self.pushButtonExitApp = QPushButton(self.PallettiererSpezifisch)
        self.pushButtonExitApp.setObjectName(u"pushButtonExitApp")
        self.pushButtonExitApp.setGeometry(QRect(760, 220, 152, 81))
        self.tabWidget_2.addTab(self.PallettiererSpezifisch, "")
        self.adminSettingsTab = QWidget()
        self.adminSettingsTab.setObjectName(u"adminSettingsTab")
        self.ButtonZurueck_4 = QPushButton(self.adminSettingsTab)
        self.ButtonZurueck_4.setObjectName(u"ButtonZurueck_4")
        self.ButtonZurueck_4.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_4.setIcon(icon3)
        self.ButtonZurueck_4.setIconSize(QSize(81, 81))
        self.ButtonZurueck_4.setFlat(True)
        self.formLayoutWidget_3 = QWidget(self.adminSettingsTab)
        self.formLayoutWidget_3.setObjectName(u"formLayoutWidget_3")
        self.formLayoutWidget_3.setGeometry(QRect(100, 10, 551, 341))
        self.formLayout_3 = QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName(u"label_8")

        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.label_8)

        self.passwordEdit = QLineEdit(self.formLayoutWidget_3)
        self.passwordEdit.setObjectName(u"passwordEdit")
        self.passwordEdit.setInputMethodHints(Qt.ImhNoAutoUppercase|Qt.ImhNoPredictiveText|Qt.ImhPreferNumbers|Qt.ImhSensitiveData)
        self.passwordEdit.setMaxLength(8)
        self.passwordEdit.setEchoMode(QLineEdit.PasswordEchoOnEdit)
        self.passwordEdit.setClearButtonEnabled(True)

        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.passwordEdit)

        self.label_24 = QLabel(self.formLayoutWidget_3)
        self.label_24.setObjectName(u"label_24")

        self.formLayout_3.setWidget(1, QFormLayout.LabelRole, self.label_24)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pathEdit = QLineEdit(self.formLayoutWidget_3)
        self.pathEdit.setObjectName(u"pathEdit")

        self.horizontalLayout.addWidget(self.pathEdit)

        self.buttonSelectRobPath = QToolButton(self.formLayoutWidget_3)
        self.buttonSelectRobPath.setObjectName(u"buttonSelectRobPath")
        self.buttonSelectRobPath.setPopupMode(QToolButton.InstantPopup)

        self.horizontalLayout.addWidget(self.buttonSelectRobPath)


        self.formLayout_3.setLayout(1, QFormLayout.FieldRole, self.horizontalLayout)

        self.label_25 = QLabel(self.formLayoutWidget_3)
        self.label_25.setObjectName(u"label_25")

        self.formLayout_3.setWidget(2, QFormLayout.LabelRole, self.label_25)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.audioPathEdit = QLineEdit(self.formLayoutWidget_3)
        self.audioPathEdit.setObjectName(u"audioPathEdit")

        self.horizontalLayout_2.addWidget(self.audioPathEdit)

        self.buttonSelectAudioFilePath = QToolButton(self.formLayoutWidget_3)
        self.buttonSelectAudioFilePath.setObjectName(u"buttonSelectAudioFilePath")
        self.buttonSelectAudioFilePath.setPopupMode(QToolButton.InstantPopup)

        self.horizontalLayout_2.addWidget(self.buttonSelectAudioFilePath)


        self.formLayout_3.setLayout(2, QFormLayout.FieldRole, self.horizontalLayout_2)

        self.formLayoutWidget_4 = QWidget(self.adminSettingsTab)
        self.formLayoutWidget_4.setObjectName(u"formLayoutWidget_4")
        self.formLayoutWidget_4.setGeometry(QRect(690, 10, 551, 341))
        self.formLayout_4 = QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setObjectName(u"formLayout_4")
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushButtonSpeichern_2 = QPushButton(self.adminSettingsTab)
        self.pushButtonSpeichern_2.setObjectName(u"pushButtonSpeichern_2")
        self.pushButtonSpeichern_2.setGeometry(QRect(4, 15, 91, 24))
        self.tabWidget_2.addTab(self.adminSettingsTab, "")
        self.editorSettingsTab = QWidget()
        self.editorSettingsTab.setObjectName(u"editorSettingsTab")
        self.ButtonZurueck_5 = QPushButton(self.editorSettingsTab)
        self.ButtonZurueck_5.setObjectName(u"ButtonZurueck_5")
        self.ButtonZurueck_5.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_5.setIcon(icon3)
        self.ButtonZurueck_5.setIconSize(QSize(81, 81))
        self.ButtonZurueck_5.setFlat(True)
        self.pushButtonSpeichern_3 = QPushButton(self.editorSettingsTab)
        self.pushButtonSpeichern_3.setObjectName(u"pushButtonSpeichern_3")
        self.pushButtonSpeichern_3.setGeometry(QRect(4, 15, 91, 24))
        self.lineEditFilePath = QLineEdit(self.editorSettingsTab)
        self.lineEditFilePath.setObjectName(u"lineEditFilePath")
        self.lineEditFilePath.setGeometry(QRect(130, 9, 1041, 22))
        self.pushButtonOpenFile = QPushButton(self.editorSettingsTab)
        self.pushButtonOpenFile.setObjectName(u"pushButtonOpenFile")
        self.pushButtonOpenFile.setGeometry(QRect(1176, 8, 75, 24))
        self.textEditFile = QTextEdit(self.editorSettingsTab)
        self.textEditFile.setObjectName(u"textEditFile")
        self.textEditFile.setGeometry(QRect(130, 30, 1121, 331))
        self.tabWidget_2.addTab(self.editorSettingsTab, "")
        self.explorerSettingsTab = QWidget()
        self.explorerSettingsTab.setObjectName(u"explorerSettingsTab")
        self.ButtonZurueck_6 = QPushButton(self.explorerSettingsTab)
        self.ButtonZurueck_6.setObjectName(u"ButtonZurueck_6")
        self.ButtonZurueck_6.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_6.setIcon(icon3)
        self.ButtonZurueck_6.setIconSize(QSize(81, 81))
        self.ButtonZurueck_6.setFlat(True)
        self.pushButtonSpeichern_4 = QPushButton(self.explorerSettingsTab)
        self.pushButtonSpeichern_4.setObjectName(u"pushButtonSpeichern_4")
        self.pushButtonSpeichern_4.setGeometry(QRect(4, 15, 91, 24))
        self.treeView = QTreeView(self.explorerSettingsTab)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(110, 0, 1141, 361))
        self.tabWidget_2.addTab(self.explorerSettingsTab, "")
        self.consoleSettingsTab = QWidget()
        self.consoleSettingsTab.setObjectName(u"consoleSettingsTab")
        self.textEditConsole = QTextEdit(self.consoleSettingsTab)
        self.textEditConsole.setObjectName(u"textEditConsole")
        self.textEditConsole.setGeometry(QRect(90, 0, 1151, 331))
        self.ButtonZurueck_7 = QPushButton(self.consoleSettingsTab)
        self.ButtonZurueck_7.setObjectName(u"ButtonZurueck_7")
        self.ButtonZurueck_7.setGeometry(QRect(0, 130, 81, 81))
        self.ButtonZurueck_7.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_7.setIcon(icon3)
        self.ButtonZurueck_7.setIconSize(QSize(81, 81))
        self.ButtonZurueck_7.setFlat(True)
        self.lineEditCommand = QLineEdit(self.consoleSettingsTab)
        self.lineEditCommand.setObjectName(u"lineEditCommand")
        self.lineEditCommand.setGeometry(QRect(90, 330, 1151, 22))
        self.tabWidget_2.addTab(self.consoleSettingsTab, "")
        self.stackedWidget.addWidget(self.Settings)
        self.Experimental = QWidget()
        self.Experimental.setObjectName(u"Experimental")
        self.availableRobFiles = QLabel(self.Experimental)
        self.availableRobFiles.setObjectName(u"availableRobFiles")
        self.availableRobFiles.setGeometry(QRect(100, 0, 201, 31))
        self.ButtonZurueck_8 = QPushButton(self.Experimental)
        self.ButtonZurueck_8.setObjectName(u"ButtonZurueck_8")
        self.ButtonZurueck_8.setGeometry(QRect(0, 270, 81, 81))
        self.ButtonZurueck_8.setCursor(QCursor(Qt.PointingHandCursor))
        self.ButtonZurueck_8.setIcon(icon3)
        self.ButtonZurueck_8.setIconSize(QSize(81, 81))
        self.ButtonZurueck_8.setFlat(True)
        self.robFilesListWidget = QListWidget(self.Experimental)
        self.robFilesListWidget.setObjectName(u"robFilesListWidget")
        self.robFilesListWidget.setGeometry(QRect(100, 30, 181, 641))
        
        self.deselectRobFile = QPushButton(self.Experimental)
        self.deselectRobFile.setObjectName(u"deselectRobFile")
        self.deselectRobFile.setGeometry(QRect(100, 680, 181, 24))
        
        self.MatplotLibCanvasFrame = QFrame(self.Experimental)
        self.MatplotLibCanvasFrame.setObjectName(u"MatplotLibCanvasFrame")
        self.MatplotLibCanvasFrame.setGeometry(QRect(290, 30, 971, 671))
        self.MatplotLibCanvasFrame.setFrameShape(QFrame.StyledPanel)
        self.MatplotLibCanvasFrame.setFrameShadow(QFrame.Raised)
        self.LadePallettenplan_2 = QPushButton(self.Experimental)
        self.LadePallettenplan_2.setObjectName(u"LadePallettenplan_2")
        self.LadePallettenplan_2.setGeometry(QRect(20, 30, 60, 60))
        sizePolicy1.setHeightForWidth(self.LadePallettenplan_2.sizePolicy().hasHeightForWidth())
        self.LadePallettenplan_2.setSizePolicy(sizePolicy1)
        self.LadePallettenplan_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.LadePallettenplan_2.setFocusPolicy(Qt.StrongFocus)
        self.LadePallettenplan_2.setIcon(icon1)
        self.LadePallettenplan_2.setIconSize(QSize(60, 60))
        self.LadePallettenplan_2.setFlat(True)
        self.stackedWidget.addWidget(self.Experimental)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(3)
        self.ButtonSettings.setDefault(False)
        self.pushButtonVolumeOnOff.setDefault(False)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Palletierer", None))
        self.ButtonSettings.setText("")
        self.checkBoxEinzelpaket.setText(QCoreApplication.translate("Form", u"Einzelpaket l\u00e4ngs", None))
        self.ButtonDatenSenden.setText(QCoreApplication.translate("Form", u"Server starten", None))
        self.ButtonOpenParameterRoboter.setText(QCoreApplication.translate("Form", u"Parameter Roboter", None))
        self.label_7.setText("")
        self.LabelPalletenplanInfo.setText("")
        self.label_9.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>mm</p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"<html><head/><body><p>kg</p></body></html>", None))
        self.EingabePallettenplan.setPlaceholderText(QCoreApplication.translate("Form", u"z.B: 699-00120", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Gewicht: </p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Palletierplan: </p></body></html>", None))
        self.LadePallettenplan.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Startlage: </p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"right\">Kartonh\u00f6he: </p></body></html>", None))
        self.pushButtonVolumeOnOff.setText("")
        self.startaudio.setText(QCoreApplication.translate("Form", u"start", None))
        self.stopaudio.setText(QCoreApplication.translate("Form", u"stop", None))
        self.openExperimentalTab.setText(QCoreApplication.translate("Form", u"Experimental", None))
        self.ButtonZurueck.setText("")
        self.ImageSzaidelLogoBig.setText("")
        self.ButtonRoboterStop.setText(QCoreApplication.translate("Form", u"Roboter Stop", None))
        self.ButtonRoboterStart.setText(QCoreApplication.translate("Form", u"Roboter Start", None))
        self.ButtonStopRPCServer.setText(QCoreApplication.translate("Form", u"Stop RPC Server", None))
        self.ButtonRoboterPause.setText(QCoreApplication.translate("Form", u"Roboter Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Roboter), QCoreApplication.translate("Form", u"Roboter", None))
        self.ButtonZurueck_2.setText("")
        self.ImageAufnahmePos.setText("")
#if QT_CONFIG(whatsthis)
        self.label_5.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Gibt die Verschiebung in Richtung x an.</p><p>min. -20mm</p><p>max.  20mm</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_5.setText(QCoreApplication.translate("Form", u"verschieben in Richtung x von:", None))
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("Form", u"<html><head/><body><p>Gibt die Verschiebung in Richtung y an.</p><p>min. -20mm</p><p>max. 20mm</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_6.setText(QCoreApplication.translate("Form", u"verschieben in Richtung y von:", None))
        self.EingabeVerschiebungX.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.EingabeVerschiebungY.setSuffix(QCoreApplication.translate("Form", u" mm", None))
        self.ButtonDatenSenden_2.setText(QCoreApplication.translate("Form", u"Daten senden", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Aufnahme), QCoreApplication.translate("Form", u"Aufnahme", None))
        self.ButtonZurueck_3.setText("")
        self.label_11.setText(QCoreApplication.translate("Form", u"UR Model: ", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"UR Serial #: ", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"UR Manufacturing Date: ", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"UR Software Ver.: ", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Pallettierer Name: ", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Pallettierer Standort: ", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Number of Plans: ", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Number of use cycles: ", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"last restart: ", None))
        self.comboBoxChooseURModel.setItemText(0, QCoreApplication.translate("Form", u"UR10", None))
        self.comboBoxChooseURModel.setItemText(1, QCoreApplication.translate("Form", u"UR20", None))

        self.comboBoxChooseURModel.setCurrentText(QCoreApplication.translate("Form", u"UR10", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Display Model: ", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"Refresh rate: ", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"Display width: ", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Display height", None))
        self.pushButtonSpeichern.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.pushButtonSearchUpdate.setText(QCoreApplication.translate("Form", u"Search Update", None))
        self.pushButtonExitApp.setText(QCoreApplication.translate("Form", u"Restart\n"
"Application", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.PallettiererSpezifisch), QCoreApplication.translate("Form", u"Info", None))
        self.ButtonZurueck_4.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"Passwort: ", None))
        self.passwordEdit.setInputMask(QCoreApplication.translate("Form", u"XXXXXXXX", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"Pfad Palettenplaene", None))
        self.buttonSelectRobPath.setText(QCoreApplication.translate("Form", u"...", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Pfad Audio file", None))
        self.buttonSelectAudioFilePath.setText(QCoreApplication.translate("Form", u"...", None))
        self.pushButtonSpeichern_2.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.adminSettingsTab), QCoreApplication.translate("Form", u"Admin", None))
        self.ButtonZurueck_5.setText("")
        self.pushButtonSpeichern_3.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.pushButtonOpenFile.setText(QCoreApplication.translate("Form", u"Open", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.editorSettingsTab), QCoreApplication.translate("Form", u"Editor", None))
        self.ButtonZurueck_6.setText("")
        self.pushButtonSpeichern_4.setText(QCoreApplication.translate("Form", u"Speichern", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.explorerSettingsTab), QCoreApplication.translate("Form", u"Explorer", None))
#if QT_CONFIG(accessibility)
        self.consoleSettingsTab.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.ButtonZurueck_7.setText("")
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.consoleSettingsTab), QCoreApplication.translate("Form", u"Console", None))
        self.availableRobFiles.setText(QCoreApplication.translate("Form", u"Available .rob files", None))
        self.ButtonZurueck_8.setText("")
        self.deselectRobFile.setText(QCoreApplication.translate("Form", u"Deselect", None))
        self.LadePallettenplan_2.setText("")
    # retranslateUi

