#ifndef MULTIPACK_SYSTEM_ROBFILEPARSER_H
#define MULTIPACK_SYSTEM_ROBFILEPARSER_H

#include <QString>
#include <QStringList>
#include <QVector>
#include <QDateTime>
#include <QFile>
#include <QTextStream>
#include <QDir>
#include <QStandardPaths>
#include <optional>
#include <tuple>

namespace multipack {

/**
 * @brief Structure to hold parsed .rob file data
 * 
 * This structure mirrors the global variables used in the Python version
 * and contains all the data parsed from a .rob file.
 */
struct RobFileData {
    // File information
    QString filePath;
    QDateTime fileTimestamp;
    
    // Core data arrays
    QVector<QVector<int>> g_Daten;              // 2D array containing all data from .rob file
    QVector<int> g_LageZuordnung;              // Layer assignments
    QVector<QVector<int>> g_PaketPos;           // Package positions (9 values per package)
    QVector<int> g_PaketeZuordnung;            // Number of packages per layer type
    QVector<int> g_Zwischenlagen;              // Intermediate layer flags
    
    // Dimensions and counts
    QVector<int> g_PalettenDim;                // Palette dimensions [length, width, height]
    QVector<int> g_PaketDim;                   // Package dimensions [length, width, height, gap]
    int g_LageArten;                           // Number of layer types
    int g_AnzLagen;                            // Number of layers
    int g_AnzahlPakete;                        // Total number of packages (deprecated: number of picks for multipick)
    
    // Other properties
    int g_paket_quer = 1;                      // Package orientation flag
    QVector<double> g_CenterOfGravity = {0, 0, 0}; // Center of gravity [x, y, z]
    
    // Status
    bool isValid = false;
    QString errorMessage;
};

/**
 * @brief Parser for .rob files from Multipack software
 * 
 * This class handles parsing of .rob files generated by Multipack palette optimization software.
 * The files contain tab-separated values with a specific structure:
 * - Line 1: Pallet dimensions (length, width, height)
 * - Line 2: Package dimensions (length, width, height, gap)
 * - Line 3: Number of layer types
 * - Line 4: Number of layers
 * - Lines 5+: Layer assignments and intermediate layers
 * - Remaining lines: Package positions for each layer type
 */
class RobFileParser {
public:
    /**
     * @brief Data structure indices (matching Python constants)
     */
    enum ListIndex {
        LI_PALETTE_DATA = 0,      // Palette data index
        LI_PACKAGE_DATA = 1,      // Package data index
        LI_LAYERTYPES = 2,        // Layer types index
        LI_NUMBER_OF_LAYERS = 3   // Number of layers index
    };
    
    /**
     * @brief Palette data indices
     */
    enum PaletteDataIndex {
        LI_PALETTE_DATA_LENGTH = 0,  // Length index
        LI_PALETTE_DATA_WIDTH = 1,   // Width index
        LI_PALETTE_DATA_HEIGHT = 2   // Height index
    };
    
    /**
     * @brief Package data indices
     */
    enum PackageDataIndex {
        LI_PACKAGE_DATA_LENGTH = 0,  // Length index
        LI_PACKAGE_DATA_WIDTH = 1,   // Width index
        LI_PACKAGE_DATA_HEIGHT = 2,  // Height index
        LI_PACKAGE_DATA_GAP = 3      // Gap index
    };
    
    /**
     * @brief Package position data indices
     */
    enum PositionIndex {
        LI_POSITION_XP = 0,     // X position (pick)
        LI_POSITION_YP = 1,     // Y position (pick)
        LI_POSITION_AP = 2,     // Angle (pick)
        LI_POSITION_XD = 3,     // X position (drop)
        LI_POSITION_YD = 4,     // Y position (drop)
        LI_POSITION_AD = 5,     // Angle (drop)
        LI_POSITION_NOP = 6,    // Number of packages
        LI_POSITION_XVEC = 7,   // X vector
        LI_POSITION_YVEC = 8    // Y vector
    };

public:
    /**
     * @brief Constructor
     * @param usbPath Path to USB stick directory (default: "..")
     */
    explicit RobFileParser(const QString& usbPath = "..");
    
    /**
     * @brief Parse a .rob file
     * @param filename Name of the .rob file to parse
     * @return RobFileData structure containing parsed data
     */
    RobFileData parseFile(const QString& filename);
    
    /**
     * @brief Parse a .rob file with full path
     * @param fullPath Full path to the .rob file
     * @return RobFileData structure containing parsed data
     */
    RobFileData parseFileFullPath(const QString& fullPath);
    
    /**
     * @brief Validate if a file is a valid .rob file
     * @param filename Name of the file to validate
     * @return true if valid .rob file, false otherwise
     */
    bool isValidRobFile(const QString& filename);
    
    /**
     * @brief Get list of available .rob files in USB directory
     * @return List of .rob file names
     */
    QStringList getAvailableRobFiles();
    
    /**
     * @brief Set USB stick path
     * @param path New USB stick path
     */
    void setUsbPath(const QString& path);
    
    /**
     * @brief Get current USB stick path
     * @return Current USB stick path
     */
    QString getUsbPath() const;

private:
    QString m_usbPath;
    
    /**
     * @brief Try to read file with different encodings
     * @param filePath Full path to file
     * @return List of parsed integer lines, or empty if failed
     */
    QVector<QVector<int>> readFileWithEncodings(const QString& filePath);
    
    /**
     * @brief Parse the data array into structured data
     * @param data Raw 2D data array from file
     * @return RobFileData structure with parsed data
     */
    RobFileData parseDataArray(const QVector<QVector<int>>& data, const QString& filePath);
    
    /**
     * @brief Get file modification timestamp
     * @param filePath Full path to file
     * @return File timestamp, or invalid QDateTime if failed
     */
    QDateTime getFileTimestamp(const QString& filePath);
    
    /**
     * @brief Validate parsed data structure
     * @param data RobFileData to validate
     * @return true if valid, false otherwise
     */
    bool validateParsedData(RobFileData& data);
    
    /**
     * @brief Convert line to integer vector
     * @param line String line containing tab-separated values
     * @return Vector of integers
     */
    QVector<int> lineToIntVector(const QString& line);
};

} // namespace multipack

#endif // MULTIPACK_SYSTEM_ROBFILEPARSER_H