name: Build Binary
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    paths:
      - "**.py"
    branches:
      - main
      - dev-more-class-files

env:
  IMAGE_NAME: multipackparser-builder
  EXECUTABLE_NAME: MultipackParser
  EXECUTABLE_DIR_IN_DOCKER: /app/dist
  EXECUTABLE_PATH_IN_DOCKER: /app/dist/MultipackParser

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/arm64 -t ${{ env.IMAGE_NAME }} --output type=docker .

      - name: Create container and extract binary
        run: |
          container_id=$(docker create ${{ env.IMAGE_NAME }})
          mkdir -p ./output
          docker cp $container_id:${{ env.EXECUTABLE_PATH_IN_DOCKER }} ./output/${{ env.EXECUTABLE_NAME }}
          docker rm $container_id

      - name: Upload binary to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXECUTABLE_NAME }}
          path: ./output/${{ env.EXECUTABLE_NAME }}

      - name: Check if VERSION changed
        id: check_version_change
        run: |
          # Fetch full history for comparison
          git fetch --unshallow

          # Get the current and previous commit SHAs
          CURR_SHA=${{ github.sha }}
          PREV_SHA=$(git rev-parse HEAD^ || echo "")

          if [ -z "$PREV_SHA" ]; then
            # If this is the first commit, there's no previous version
            echo "No previous commit found. Skipping version check."
            echo "should_continue=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get versions from current and previous commit
          PREV_VERSION=$(git show $PREV_SHA:utils/global_vars.py | grep -m 1 "VERSION = " | cut -d "'" -f 2 || echo "")
          CURR_VERSION=$(git show $CURR_SHA:utils/global_vars.py | grep -m 1 "VERSION = " | cut -d "'" -f 2)

          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURR_VERSION"

          if [ "$PREV_VERSION" == "$CURR_VERSION" ]; then
            echo "No VERSION change detected. Skipping release."
            echo "should_continue=false" >> $GITHUB_OUTPUT
          else
            echo "Version changed from $PREV_VERSION to $CURR_VERSION"
            echo "should_continue=true" >> $GITHUB_OUTPUT
            echo "version=$CURR_VERSION" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Get version
        id: get_version
        if: steps.check_version_change.outputs.should_continue == 'true'
        run: |
          VERSION="${{ steps.check_version_change.outputs.version }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          echo "release_name=Release v${VERSION}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Fetch all tags
        if: steps.check_version_change.outputs.should_continue == 'true'
        run: git fetch --tags --force

      - name: Get latest tag
        if: steps.check_version_change.outputs.should_continue == 'true'
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        if: steps.check_version_change.outputs.should_continue == 'true'
        id: check_tag
        run: |
          if [ "${{ steps.get_version.outputs.tag_name }}" == "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "Tag ${{ steps.get_version.outputs.tag_name }} already exists. Stopping the workflow."
            exit 1
          fi
        shell: bash

      - name: Release
        if: steps.check_version_change.outputs.should_continue == 'true'
        uses: softprops/action-gh-release@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: ${{ steps.get_version.outputs.release_name }}
          files: ./output/${{ env.EXECUTABLE_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          make_latest: true
