name: Build and Release Binary
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - dev-more-class-files

env:
  IMAGE_NAME: multipackparser-builder
  EXECUTABLE_NAME: MultipackParser
  EXECUTABLE_DIR_IN_DOCKER: /app/dist
  EXECUTABLE_PATH_IN_DOCKER: /app/dist/MultipackParser

jobs:
  build-and-release-binary:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '--build')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/arm64 -t ${{ env.IMAGE_NAME }} --output type=docker .

      - name: Create container and extract binary
        run: |
          container_id=$(docker create ${{ env.IMAGE_NAME }})
          mkdir -p ./output
          docker cp $container_id:${{ env.EXECUTABLE_PATH_IN_DOCKER }} ./output/${{ env.EXECUTABLE_NAME }}
          docker rm $container_id

      - name: Upload binary to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXECUTABLE_NAME }}
          path: ./output/${{ env.EXECUTABLE_NAME }}

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set working directory
        run: cd ${{ github.workspace }}

      - name: Get version
        id: get_version
        run: |
          VERSION_LINE=$(grep -m 1 "VERSION = " utils/global_vars.py || echo "VERSION not found")
          if [[ $VERSION_LINE == *"VERSION not found"* ]]; then
            echo "Error: VERSION not found in global_vars.py"
            exit 1
          fi
          VERSION=$(echo $VERSION_LINE | cut -d "'" -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          echo "release_name=Release v${VERSION}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Fetch all tags
        run: git fetch --tags --force
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
      
      - name: Check if tag already exists
        id: check_tag
        run: |
          if [ "${{ steps.get_version.outputs.tag_name }}" == "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "Tag ${{ steps.get_version.outputs.tag_name }} already exists. Stopping the workflow."
            exit 1
          fi
        shell: bash


      - name: Notify committer if tag exists
        if: always()
        run: |
          if [ "${{ steps.get_version.outputs.tag_name }}" == "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "Notify the committer about the existing tag."
          fi

      - name: Create GitHub Release
        id: create_release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          release_name: ${{ steps.get_version.outputs.release_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/MultipackParser
          asset_name: MultipackParser
          asset_content_type: application/octet-stream
