name: Release Binary
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    paths:
      - 'utils/global_vars.py'

env:
  EXECUTABLE_NAME: MultipackParser

jobs:
  release-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          VERSION_LINE=$(grep -m 1 "VERSION = " utils/global_vars.py || echo "VERSION not found")
          if [[ $VERSION_LINE == *"VERSION not found"* ]]; then
            echo "Error: VERSION not found in global_vars.py"
            exit 1
          fi
          VERSION=$(echo $VERSION_LINE | cut -d "'" -f 2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT
          echo "release_name=Release v${VERSION}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Fetch all tags
        run: git fetch --tags --force
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
      
      - name: Check if tag already exists
        id: check_tag
        run: |
          if [ "${{ steps.get_version.outputs.tag_name }}" == "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "Tag ${{ steps.get_version.outputs.tag_name }} already exists. Stopping the workflow."
            exit 1
          fi
        shell: bash

      - name: Download artifact from latest build
        uses: dawidd6/action-download-artifact@v6
        with:
          name: ${{ env.EXECUTABLE_NAME }}
          path: ./output
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: ${{ steps.get_version.outputs.release_name }}
          files: ./output/${{ env.EXECUTABLE_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          make_latest: true 
